### PR TITLE
Enhancements 

### PR DESCRIPTION
**Pull request by MostafaRamadan1**
1. Adding option to generate only controllerDto
2. Adding option to specify dto package name
3. Adding option to specify mapper package name
4. Adding option to exclude generation of CrudController interface
5. Adding option to exclude generation of CrudService interface
6. Fix reading verb in controller
7. Remove extra imports from Dto
8. Remove static project path from setting yaml in testing and update output package

### CODE REVIEW

**Comment by GaetanoPiazzolla** [comment]
Great job mostafaa. I’ll take a look at the PR in the evening

**Comment by GaetanoPiazzolla** [comment]
Hey, @MostafaaRamadan1 thanks for the update.
I've added some comments. 

Please can you also: 
- update the library version number
- update the "demo" code?

Thanks!

**Comment by MostafaRamadan1** [comment]
can you please explain more on how to update the demo and demo-jakarata package

**Comment by MostafaRamadan1** [comment]
@GaetanoPiazzolla I have updated both demo and jakarata packages, and versioned up the plugin to be 1.9, unfortunately I don't have java 11, and couldn't do a sanity check, so please do a sanity check for this branch if all tests from your side passed, we can release new version then.

**Comment by GaetanoPiazzolla** [comment]
There are still some comments in the MR that needs review. Also, in 
3layer-settings.yaml and 3layer-settings-yakarta in the test used to generate the changes, it's used "serviceInterface" while you committed files with "service".

Please update those "demo" folder by running that tests, and make sure that both the "demo" and "demo-jackarta" build correctly after the generation.
Also, the demo build.gradle should still be using the version 1.8 until we push the new version in gradle repo.

**Comment by MostafaRamadan1** [comment]
I was able to generate the demo package doing the following set my java version to be 11, build the demo project by ./gradlew clean build, then run the testing method to generate the demo.

But when I do the run the testing method for generating the jakarata demo package, I can not see the entities, by reflection

```
private static Set<Class<?>> getEntityClasses() {
        Reflections reflections = new Reflections(config.getInputPackages().getJpaEntities(), classLoader);
        Set<Class<?>> classes = reflections.getTypesAnnotatedWith(javax.persistence.Entity.class);
        classes.addAll(reflections.getTypesAnnotatedWith(jakarta.persistence.Entity.class));
        return classes;
    }  
```

this below code, not working for some reason
`reflections.getTypesAnnotatedWith(jakarta.persistence.Entity.class)`

**Comment by GaetanoPiazzolla** [comment]
Probably because you need to have the .class already generated in the build
directory, then you can read them. Can you try?
Also, please remove the update to the read me. Just add the new
functionalities in the already present snippet of it, no need to add an
enhancement section.
Remember to update the library version there as well.
Thanks a lot for your effort!
Want to merge this pr asap.

Il giorno mar 21 feb 2023 alle 07:51 Mostafa Ramadan <
***@***.***> ha scritto:

**Comment by MostafaRamadan1** [comment]
I understand your comment, as you must build the project first, to generate models in build directory, and then by reflection you you able to see those entities. Unfortunately didn't work from my side.

I did install java 19, then build the jakarta project, and after that, tried to run the test case in the main project, but I hit the wall due to the project in not a java 19 project.

I will try again, but if you can do it quicker from your side, this would be great

**Comment by GaetanoPiazzolla** [comment]
Merged this PR, but I restored the JPA example entity query because I find that really useful. 
Reference: https://www.baeldung.com/spring-data-query-by-example

**Pull request merged**
